cellsociety_team10: viewPackage.ToggleBox Class Reference
viewPackage.ToggleBox Class Reference
Protected Member Functions
HBox makeToggles ()
boolean getEdgeType ()
boolean getOutline ()
boolean getShape ()
Package Attributes
ToggleGroup cellShape
ToggleGroup outline
Private Member Functions
ToggleButton createToggleButton (String name, ToggleGroup group, boolean depressed)
VBox createToggleGroup (ToggleGroup x, String bt1, String bt2)
VBox assignToVBox (ToggleButton tb1, ToggleButton tb2)
void setToggleProperty (ToggleGroup group, ToggleButton tb1, ToggleButton tb2)
void setToggleChangeMethod (ToggleGroup groupName, boolean change)
Private Attributes
ToggleGroup edgeType
boolean isTriangleShape
boolean isToroidalEdgeType
boolean isNoStroke
Detailed Description
Definition at line 12 of file ToggleBox.java.
Member Function Documentation
VBox viewPackage.ToggleBox.assignToVBox (ToggleButton tb1, ToggleButton tb2) private
Definition at line 64 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.createToggleGroup(), and viewPackage.ToggleBox.makeToggles().
ToggleButton viewPackage.ToggleBox.createToggleButton (String name, ToggleGroup group, boolean depressed) private
Definition at line 19 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.createToggleGroup(), and viewPackage.ToggleBox.makeToggles().
VBox viewPackage.ToggleBox.createToggleGroup (ToggleGroup x, String bt1, String bt2) private
Definition at line 26 of file ToggleBox.java.
References viewPackage.ToggleBox.assignToVBox(), viewPackage.ToggleBox.createToggleButton(), and viewPackage.ToggleBox.setToggleProperty().
boolean viewPackage.ToggleBox.getEdgeType () protected
Definition at line 99 of file ToggleBox.java.
References viewPackage.ToggleBox.isToroidalEdgeType.
Referenced by viewPackage.View.getEdgeType().
boolean viewPackage.ToggleBox.getOutline () protected
Definition at line 103 of file ToggleBox.java.
References viewPackage.ToggleBox.isNoStroke.
Referenced by viewPackage.View.getOutline().
boolean viewPackage.ToggleBox.getShape () protected
Definition at line 107 of file ToggleBox.java.
References viewPackage.ToggleBox.isTriangleShape.
Referenced by viewPackage.View.createDisplayView().
HBox viewPackage.ToggleBox.makeToggles () protected
Definition at line 35 of file ToggleBox.java.
References viewPackage.ToggleBox.assignToVBox(), viewPackage.ToggleBox.createToggleButton(), and viewPackage.ToggleBox.setToggleProperty().
Referenced by viewPackage.View.initialize().
void viewPackage.ToggleBox.setToggleChangeMethod (ToggleGroup groupName, boolean change) private
Definition at line 87 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.setToggleProperty().
void viewPackage.ToggleBox.setToggleProperty (ToggleGroup group, ToggleButton tb1, ToggleButton tb2) private
Definition at line 71 of file ToggleBox.java.
References viewPackage.ToggleBox.setToggleChangeMethod().
Referenced by viewPackage.ToggleBox.createToggleGroup(), and viewPackage.ToggleBox.makeToggles().
Member Data Documentation
ToggleGroup viewPackage.ToggleBox.cellShape package
Definition at line 14 of file ToggleBox.java.
ToggleGroup viewPackage.ToggleBox.edgeType private
Definition at line 14 of file ToggleBox.java.
boolean viewPackage.ToggleBox.isNoStroke private
Definition at line 17 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.getOutline().
boolean viewPackage.ToggleBox.isToroidalEdgeType private
Definition at line 16 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.getEdgeType().
boolean viewPackage.ToggleBox.isTriangleShape private
Definition at line 15 of file ToggleBox.java.
Referenced by viewPackage.ToggleBox.getShape().
ToggleGroup viewPackage.ToggleBox.outline package
Definition at line 14 of file ToggleBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/ToggleBox.java