cellsociety_team10: model.Cell Class Reference
model.Cell Class Reference
Public Member Functions
Cell (CellState setState, Map< String, Integer > attributes)
Cell copyCell ()
void changeToEmptyCell ()
Map< String, Integer > getProperties ()
CellState getState ()
void setState (CellState cs)
String toString ()
Integer getKey (String key)
Private Attributes
CellState state
Map< String, Integer > properties
Detailed Description
general cell class
Author
GA
Definition at line 13 of file Cell.java.
Constructor & Destructor Documentation
model.Cell.Cell (CellState setState, Map< String, Integer > attributes)
Definition at line 18 of file Cell.java.
References model.Cell.setState().
Referenced by model.Cell.copyCell().
Member Function Documentation
void model.Cell.changeToEmptyCell ()
Definition at line 27 of file Cell.java.
References model.CellState.EMPTY.
Referenced by model.WatorSimulation.moveCreature(), and model.WatorSimulation.removeCreature().
Cell model.Cell.copyCell ()
Definition at line 23 of file Cell.java.
References model.Cell.Cell(), model.Cell.getState(), and model.Cell.properties.
Integer model.Cell.getKey (String key)
Definition at line 48 of file Cell.java.
Referenced by model.FireSimulation.calculateNewCellState(), model.SegregationSimulation.calculateNewCellState(), model.WatorSimulation.canReproduce(), and model.WatorSimulation.sharkAction().
Map<String, Integer> model.Cell.getProperties ()
Definition at line 31 of file Cell.java.
References model.Cell.properties.
Referenced by model.WatorSimulation.decreaseEnergy(), model.WatorSimulation.fishAction(), model.WatorSimulation.increaseBreedingTime(), model.Grid.print(), model.WatorSimulation.resetBreedTime(), and model.WatorSimulation.sharkAction().
CellState model.Cell.getState ()
Definition at line 34 of file Cell.java.
References model.Cell.state.
Referenced by model.GameLifeSimulation.calculateNewCellState(), model.FireSimulation.calculateNewCellState(), model.SegregationSimulation.calculateNewCellState(), model.Cell.copyCell(), and model.Grid.getLocationsWithState().
void model.Cell.setState (CellState cs)
Definition at line 37 of file Cell.java.
Referenced by model.Cell.Cell(), and model.Simulation.makeNextGrid().
String model.Cell.toString ()
Definition at line 43 of file Cell.java.
Referenced by controller.Controller.createColorGrid(), model.Grid.print(), and controller.Controller.updateStateTotals().
Member Data Documentation
Map<String, Integer> model.Cell.properties private
Definition at line 15 of file Cell.java.
Referenced by model.Cell.copyCell(), and model.Cell.getProperties().
CellState model.Cell.state private
Definition at line 14 of file Cell.java.
Referenced by model.Cell.getState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/Cell.java