cellsociety_team10: model.Simulation Class Reference
model.Simulation Class Reference abstract
Public Member Functions
Simulation (Grid aGrid, Packager attributes)
Grid getCurrentGrid ()
Grid getNextGrid ()
void setNextGrid (Grid x)
Grid makeNextGrid ()
void updateGrid (Grid x)
abstract CellState calculateNewCellState (int row, int col)
Static Public Attributes
static final Random myGenerator = new Random(1234)
Package Attributes
Grid nextGrid
Private Attributes
Grid currentGrid
Detailed Description
this abstract class will define a general structure for any type of simulation
Author
GA
Definition at line 11 of file Simulation.java.
Constructor & Destructor Documentation
model.Simulation.Simulation (Grid aGrid, Packager attributes)
Definition at line 15 of file Simulation.java.
Member Function Documentation
abstract CellState model.Simulation.calculateNewCellState (int row, int col) abstract
Referenced by model.Simulation.makeNextGrid().
Grid model.Simulation.getCurrentGrid ()
Definition at line 19 of file Simulation.java.
References model.Simulation.currentGrid.
Referenced by model.GameLifeSimulation.calculateNewCellState(), model.SegregationSimulation.calculateNewCellState(), model.WatorSimulation.canReproduce(), model.WatorSimulation.decreaseEnergy(), model.WatorSimulation.fishAction(), model.WatorSimulation.makeBaby(), model.WatorSimulation.makeNextGrid(), model.SegregationSimulation.makeNextGrid(), model.WatorSimulation.moveCreature(), and model.WatorSimulation.sharkAction().
Grid model.Simulation.getNextGrid ()
Definition at line 22 of file Simulation.java.
References model.Simulation.nextGrid.
Referenced by model.WatorSimulation.decreaseEnergy(), model.WatorSimulation.fishAction(), model.WatorSimulation.increaseBreedingTime(), model.WatorSimulation.makeBaby(), model.WatorSimulation.makeNextGrid(), model.WatorSimulation.moveAndCheckBaby(), model.WatorSimulation.moveCreature(), model.WatorSimulation.moveIfEmptyAndCheckBaby(), model.WatorSimulation.removeCreature(), model.WatorSimulation.resetBreedTime(), and model.WatorSimulation.sharkAction().
Grid model.Simulation.makeNextGrid ()
Definition at line 29 of file Simulation.java.
References model.Simulation.calculateNewCellState(), model.Grid.copyGrid(), model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), model.Simulation.nextGrid, and model.Cell.setState().
Referenced by controller.Controller.stepSimulation().
void model.Simulation.setNextGrid (Grid x)
Definition at line 25 of file Simulation.java.
Referenced by model.WatorSimulation.makeNextGrid().
void model.Simulation.updateGrid (Grid x)
Definition at line 42 of file Simulation.java.
Referenced by controller.Controller.stepSimulation().
Member Data Documentation
Grid model.Simulation.currentGrid private
Definition at line 12 of file Simulation.java.
Referenced by model.Simulation.getCurrentGrid().
final Random model.Simulation.myGenerator = new Random(1234) static
Definition at line 13 of file Simulation.java.
Referenced by model.FireSimulation.calculateNewCellState(), model.SegregationSimulation.makeNextGrid(), model.WatorSimulation.moveIfEmptyAndCheckBaby(), and model.WatorSimulation.sharkAction().
Grid model.Simulation.nextGrid package
Definition at line 12 of file Simulation.java.
Referenced by model.Simulation.getNextGrid(), and model.Simulation.makeNextGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/Simulation.java