cellsociety_team10: controller.ViewPackager Class Reference
controller.ViewPackager Class Reference
Public Member Functions
void setColorGrid (ArrayList< ArrayList< String >> color)
ArrayList< ArrayList< String > > getColorGrid ()
Map< String, Integer > getStateTotals ()
void setStateTotalMap (Map< String, Integer > map)
Private Attributes
ArrayList< ArrayList< String > > colorGrid
Map< String, Integer > stateTotals
Detailed Description
this packager contains information the view needs: generation count, the grid of colors, the totals of each color
Author
GA
Definition at line 13 of file ViewPackager.java.
Member Function Documentation
ArrayList<ArrayList<String> > controller.ViewPackager.getColorGrid ()
Definition at line 20 of file ViewPackager.java.
References controller.ViewPackager.colorGrid.
Referenced by viewPackage.DisplayGrid.updateGrid().
Map<String, Integer> controller.ViewPackager.getStateTotals ()
Definition at line 24 of file ViewPackager.java.
Referenced by viewPackage.PopulationGraph.updateGraph().
void controller.ViewPackager.setColorGrid (ArrayList< ArrayList< String >> color)
Definition at line 17 of file ViewPackager.java.
Referenced by controller.Controller.bundleViewPackager().
void controller.ViewPackager.setStateTotalMap (Map< String, Integer > map)
Definition at line 27 of file ViewPackager.java.
Referenced by controller.Controller.bundleViewPackager().
Member Data Documentation
ArrayList<ArrayList<String> > controller.ViewPackager.colorGrid private
Definition at line 14 of file ViewPackager.java.
Referenced by controller.ViewPackager.getColorGrid().
Map<String, Integer> controller.ViewPackager.stateTotals private
Definition at line 15 of file ViewPackager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/controller/ViewPackager.java