cellsociety_team10: model.FiniteGrid Class Reference
model.FiniteGrid Class Reference
Public Member Functions
FiniteGrid (int row, int column)
List< Cell > getDirectNeighbors (int row, int col)
List< Cell > getAllNeighbors (int row, int col)
Grid copyGrid ()
Public Member Functions inherited from model.Grid
Grid (int row, int column)
Cell getCell (int row, int col)
void putCell (Cell target, int row, int col)
int getGridRowSize ()
int getGridColSize ()
void print ()
Additional Inherited Members
Protected Member Functions inherited from model.Grid
abstract List< Cell > getAllNeighbors (int row, int col)
abstract List< Cell > getDirectNeighbors (int row, int col)
ArrayList< Point > getLocationsWithState (CellState x)
List< Point > getDirectLocationsWithType (Point p, CellState c)
List< Cell > getDirectNeighborsWithType (int row, int col, CellState c)
abstract Grid copyGrid ()
boolean inBounds (int row, int col)
Detailed Description
finite grid edge where there is no wrap around grid edges
Author
GA
Definition at line 10 of file FiniteGrid.java.
Constructor & Destructor Documentation
model.FiniteGrid.FiniteGrid (int row, int column)
Definition at line 12 of file FiniteGrid.java.
Referenced by model.FiniteGrid.copyGrid().
Member Function Documentation
Grid model.FiniteGrid.copyGrid ()
Definition at line 40 of file FiniteGrid.java.
References model.FiniteGrid.FiniteGrid(), model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), and model.Grid.putCell().
List<Cell> model.FiniteGrid.getAllNeighbors (int row, int col)
Definition at line 27 of file FiniteGrid.java.
References model.Grid.getCell(), model.FiniteGrid.getDirectNeighbors(), and model.Grid.inBounds().
List<Cell> model.FiniteGrid.getDirectNeighbors (int row, int col)
Definition at line 15 of file FiniteGrid.java.
References model.Grid.getCell(), and model.Grid.inBounds().
Referenced by model.FiniteGrid.getAllNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/FiniteGrid.java