cellsociety_team10: model.Grid Class Reference
model.Grid Class Reference abstract
Public Member Functions
Grid (int row, int column)
Cell getCell (int row, int col)
void putCell (Cell target, int row, int col)
int getGridRowSize ()
int getGridColSize ()
void print ()
Protected Member Functions
abstract List< Cell > getAllNeighbors (int row, int col)
abstract List< Cell > getDirectNeighbors (int row, int col)
ArrayList< Point > getLocationsWithState (CellState x)
List< Point > getDirectLocationsWithType (Point p, CellState c)
List< Cell > getDirectNeighborsWithType (int row, int col, CellState c)
abstract Grid copyGrid ()
boolean inBounds (int row, int col)
Private Attributes
Cell[][] myCells
Detailed Description
general grid structure that contains an array of cells
Author
GA
Definition at line 14 of file Grid.java.
Constructor & Destructor Documentation
model.Grid.Grid (int row, int column)
Definition at line 18 of file Grid.java.
Member Function Documentation
abstract Grid model.Grid.copyGrid () abstract protected
Referenced by model.Simulation.makeNextGrid().
abstract List<Cell> model.Grid.getAllNeighbors (int row, int col) abstract protected
Referenced by model.GameLifeSimulation.calculateNewCellState().
Cell model.Grid.getCell (int row, int col)
Definition at line 70 of file Grid.java.
Referenced by model.GameLifeSimulation.calculateNewCellState(), model.WatorSimulation.canReproduce(), model.FiniteGrid.copyGrid(), model.ToroidalGrid.copyGrid(), controller.Controller.createColorGrid(), model.WatorSimulation.decreaseEnergy(), model.WatorSimulation.fishAction(), model.ToroidalGrid.getAllNeighbors(), model.FiniteGrid.getAllNeighbors(), model.FiniteGrid.getDirectNeighbors(), model.ToroidalGrid.getDirectNeighbors(), model.Grid.getLocationsWithState(), model.WatorSimulation.increaseBreedingTime(), model.Simulation.makeNextGrid(), model.WatorSimulation.moveCreature(), model.WatorSimulation.removeCreature(), model.WatorSimulation.resetBreedTime(), model.WatorSimulation.sharkAction(), and controller.Controller.updateStateTotals().
List<Point> model.Grid.getDirectLocationsWithType (Point p, CellState c) protected
Definition at line 35 of file Grid.java.
References model.Grid.inBounds().
Referenced by model.WatorSimulation.moveIfEmptyAndCheckBaby(), and model.WatorSimulation.sharkAction().
abstract List<Cell> model.Grid.getDirectNeighbors (int row, int col) abstract protected
List<Cell> model.Grid.getDirectNeighborsWithType (int row, int col, CellState c) protected
Definition at line 51 of file Grid.java.
References model.Grid.inBounds().
Referenced by model.SegregationSimulation.calculateNewCellState().
int model.Grid.getGridColSize ()
Definition at line 85 of file Grid.java.
Referenced by model.FiniteGrid.copyGrid(), model.ToroidalGrid.copyGrid(), controller.Controller.createColorGrid(), model.ToroidalGrid.getAllNeighbors(), model.ToroidalGrid.getDirectNeighbors(), model.Simulation.makeNextGrid(), and controller.Controller.updateStateTotals().
int model.Grid.getGridRowSize ()
Definition at line 82 of file Grid.java.
Referenced by model.FiniteGrid.copyGrid(), model.ToroidalGrid.copyGrid(), controller.Controller.createColorGrid(), model.ToroidalGrid.getAllNeighbors(), model.ToroidalGrid.getDirectNeighbors(), model.Simulation.makeNextGrid(), and controller.Controller.updateStateTotals().
ArrayList<Point> model.Grid.getLocationsWithState (CellState x) protected
Definition at line 24 of file Grid.java.
References model.Grid.getCell(), and model.Cell.getState().
Referenced by model.WatorSimulation.makeNextGrid().
boolean model.Grid.inBounds (int row, int col) protected
Definition at line 78 of file Grid.java.
Referenced by model.ToroidalGrid.getAllNeighbors(), model.FiniteGrid.getAllNeighbors(), model.Grid.getDirectLocationsWithType(), model.FiniteGrid.getDirectNeighbors(), model.ToroidalGrid.getDirectNeighbors(), and model.Grid.getDirectNeighborsWithType().
void model.Grid.print ()
Definition at line 89 of file Grid.java.
References model.Cell.getProperties(), and model.Cell.toString().
Referenced by model.WatorSimulation.makeNextGrid(), and model.SegregationSimulation.makeNextGrid().
void model.Grid.putCell (Cell target, int row, int col)
Definition at line 74 of file Grid.java.
Referenced by model.FiniteGrid.copyGrid(), model.ToroidalGrid.copyGrid(), controller.Controller.listToGrid(), model.WatorSimulation.makeBaby(), model.SegregationSimulation.makeNextGrid(), and model.WatorSimulation.moveCreature().
Member Data Documentation
Cell [][] model.Grid.myCells private
Definition at line 15 of file Grid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/Grid.java