cellsociety_team10: viewPackage.TriangularGridView Class Reference
viewPackage.TriangularGridView Class Reference
Public Member Functions
TriangularGridView (View mainView)
void initialEmptyGrid (int xtot, int ytot, double x, double y)
Public Member Functions inherited from viewPackage.DisplayGrid
DisplayGrid (View mainView)
void initializeGridView (int sizeX, int sizeY)
abstract void initialEmptyGrid (int xtot, int ytot, double x, double y)
void updateGrid (ViewPackager viewPackager)
void setToggleColorChange (Shape p)
Private Member Functions
void drawEvenTriangle (double x, double y, int i, int j, Shape p)
void drawOddTriangle (double x, double y, int i, int j, Shape p)
Additional Inherited Members
Protected Member Functions inherited from viewPackage.DisplayGrid
void outline (Shape p)
void setFill (Shape gridView, Color c)
View getView ()
void setShape (int row, int col, Shape p)
Detailed Description
Definition at line 5 of file TriangularGridView.java.
Constructor & Destructor Documentation
viewPackage.TriangularGridView.TriangularGridView (View mainView)
Definition at line 8 of file TriangularGridView.java.
Member Function Documentation
void viewPackage.TriangularGridView.drawEvenTriangle (double x, double y, int i, int j, Shape p) private
Definition at line 39 of file TriangularGridView.java.
Referenced by viewPackage.TriangularGridView.initialEmptyGrid().
void viewPackage.TriangularGridView.drawOddTriangle (double x, double y, int i, int j, Shape p) private
Definition at line 46 of file TriangularGridView.java.
Referenced by viewPackage.TriangularGridView.initialEmptyGrid().
void viewPackage.TriangularGridView.initialEmptyGrid (int xtot, int ytot, double x, double y)
Definition at line 13 of file TriangularGridView.java.
References viewPackage.View.addToRoot(), viewPackage.TriangularGridView.drawEvenTriangle(), viewPackage.TriangularGridView.drawOddTriangle(), viewPackage.DisplayGrid.getView(), and viewPackage.DisplayGrid.setShape().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/TriangularGridView.java