cellsociety_team10: model.WatorSimulation Class Reference
model.WatorSimulation Class Reference
Public Member Functions
WatorSimulation (Grid aGrid, Packager settings)
CellState calculateNewCellState (int row, int col)
Grid makeNextGrid ()
Public Member Functions inherited from model.Simulation
Simulation (Grid aGrid, Packager attributes)
Grid getCurrentGrid ()
Grid getNextGrid ()
void setNextGrid (Grid x)
Grid makeNextGrid ()
void updateGrid (Grid x)
abstract CellState calculateNewCellState (int row, int col)
Package Attributes
ArrayList< Point > allFish
Package Attributes inherited from model.Simulation
Grid nextGrid
Private Member Functions
void sharkAction ()
void moveIfEmptyAndCheckBaby (Point loc, CellState babyType)
void moveAndCheckBaby (Point loc, Point newLoc, CellState babyType)
void fishAction ()
void increaseBreedingTime (int row, int col)
void moveCreature (int y1, int x1, int y2, int x2)
void decreaseEnergy (int row, int col)
void removeCreature (List< Point > list, Point p)
void resetBreedTime (int row, int col)
void makeBaby (CellState c, Point loc)
boolean canReproduce (Point creature)
Private Attributes
ArrayList< Point > allSharks
Additional Inherited Members
Static Public Attributes inherited from model.Simulation
static final Random myGenerator = new Random(1234)
Detailed Description
Definition at line 10 of file WatorSimulation.java.
Constructor & Destructor Documentation
model.WatorSimulation.WatorSimulation (Grid aGrid, Packager settings)
Definition at line 16 of file WatorSimulation.java.
Member Function Documentation
CellState model.WatorSimulation.calculateNewCellState (int row, int col)
Definition at line 20 of file WatorSimulation.java.
boolean model.WatorSimulation.canReproduce (Point creature) private
Definition at line 143 of file WatorSimulation.java.
References model.Grid.getCell(), model.Simulation.getCurrentGrid(), and model.Cell.getKey().
Referenced by model.WatorSimulation.moveAndCheckBaby().
void model.WatorSimulation.decreaseEnergy (int row, int col) private
Definition at line 111 of file WatorSimulation.java.
References model.Grid.getCell(), model.Simulation.getCurrentGrid(), model.Simulation.getNextGrid(), and model.Cell.getProperties().
Referenced by model.WatorSimulation.sharkAction().
void model.WatorSimulation.fishAction () private
Definition at line 91 of file WatorSimulation.java.
References model.CellState.FISH, model.Grid.getCell(), model.Simulation.getCurrentGrid(), model.Simulation.getNextGrid(), model.Cell.getProperties(), and model.WatorSimulation.moveIfEmptyAndCheckBaby().
Referenced by model.WatorSimulation.makeNextGrid().
void model.WatorSimulation.increaseBreedingTime (int row, int col) private
Definition at line 100 of file WatorSimulation.java.
References model.Grid.getCell(), model.Simulation.getNextGrid(), and model.Cell.getProperties().
Referenced by model.WatorSimulation.moveAndCheckBaby(), and model.WatorSimulation.moveIfEmptyAndCheckBaby().
void model.WatorSimulation.makeBaby (CellState c, Point loc) private
Definition at line 136 of file WatorSimulation.java.
References model.Simulation.getCurrentGrid(), model.Simulation.getNextGrid(), and model.Grid.putCell().
Referenced by model.WatorSimulation.moveAndCheckBaby().
Grid model.WatorSimulation.makeNextGrid ()
Definition at line 25 of file WatorSimulation.java.
References model.CellState.FISH, model.WatorSimulation.fishAction(), model.Simulation.getCurrentGrid(), model.Grid.getLocationsWithState(), model.Simulation.getNextGrid(), model.Grid.print(), model.Simulation.setNextGrid(), model.CellState.SHARK, and model.WatorSimulation.sharkAction().
void model.WatorSimulation.moveAndCheckBaby (Point loc, Point newLoc, CellState babyType) private
Definition at line 78 of file WatorSimulation.java.
References model.WatorSimulation.canReproduce(), model.Simulation.getNextGrid(), model.WatorSimulation.increaseBreedingTime(), model.WatorSimulation.makeBaby(), model.WatorSimulation.moveCreature(), and model.WatorSimulation.resetBreedTime().
Referenced by model.WatorSimulation.moveIfEmptyAndCheckBaby(), and model.WatorSimulation.sharkAction().
void model.WatorSimulation.moveCreature (int y1, int x1, int y2, int x2) private
Definition at line 105 of file WatorSimulation.java.
References model.Cell.changeToEmptyCell(), model.Grid.getCell(), model.Simulation.getCurrentGrid(), model.Simulation.getNextGrid(), and model.Grid.putCell().
Referenced by model.WatorSimulation.moveAndCheckBaby().
void model.WatorSimulation.moveIfEmptyAndCheckBaby (Point loc, CellState babyType) private
Definition at line 66 of file WatorSimulation.java.
References model.CellState.EMPTY, model.Grid.getDirectLocationsWithType(), model.Simulation.getNextGrid(), model.WatorSimulation.increaseBreedingTime(), model.WatorSimulation.moveAndCheckBaby(), and model.Simulation.myGenerator.
Referenced by model.WatorSimulation.fishAction(), and model.WatorSimulation.sharkAction().
void model.WatorSimulation.removeCreature (List< Point > list, Point p) private
Definition at line 116 of file WatorSimulation.java.
References model.Cell.changeToEmptyCell(), model.Grid.getCell(), and model.Simulation.getNextGrid().
Referenced by model.WatorSimulation.sharkAction().
void model.WatorSimulation.resetBreedTime (int row, int col) private
Definition at line 131 of file WatorSimulation.java.
References model.Grid.getCell(), model.Simulation.getNextGrid(), and model.Cell.getProperties().
Referenced by model.WatorSimulation.moveAndCheckBaby().
void model.WatorSimulation.sharkAction () private
Definition at line 38 of file WatorSimulation.java.
References model.WatorSimulation.decreaseEnergy(), model.CellState.FISH, model.Grid.getCell(), model.Simulation.getCurrentGrid(), model.Grid.getDirectLocationsWithType(), model.Cell.getKey(), model.Simulation.getNextGrid(), model.Cell.getProperties(), model.WatorSimulation.moveAndCheckBaby(), model.WatorSimulation.moveIfEmptyAndCheckBaby(), model.Simulation.myGenerator, model.WatorSimulation.removeCreature(), and model.CellState.SHARK.
Referenced by model.WatorSimulation.makeNextGrid().
Member Data Documentation
ArrayList<Point> model.WatorSimulation.allFish package
Definition at line 11 of file WatorSimulation.java.
ArrayList<Point> model.WatorSimulation.allSharks private
Definition at line 11 of file WatorSimulation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/WatorSimulation.java