cellsociety_team10: model.ToroidalGrid Class Reference
model.ToroidalGrid Class Reference
Public Member Functions
ToroidalGrid (int row, int column)
List< Cell > getAllNeighbors (int row, int col)
List< Cell > getDirectNeighbors (int row, int col)
Grid copyGrid ()
Public Member Functions inherited from model.Grid
Grid (int row, int column)
Cell getCell (int row, int col)
void putCell (Cell target, int row, int col)
int getGridRowSize ()
int getGridColSize ()
void print ()
Additional Inherited Members
Protected Member Functions inherited from model.Grid
abstract List< Cell > getAllNeighbors (int row, int col)
abstract List< Cell > getDirectNeighbors (int row, int col)
ArrayList< Point > getLocationsWithState (CellState x)
List< Point > getDirectLocationsWithType (Point p, CellState c)
List< Cell > getDirectNeighborsWithType (int row, int col, CellState c)
abstract Grid copyGrid ()
boolean inBounds (int row, int col)
Detailed Description
Definition at line 6 of file ToroidalGrid.java.
Constructor & Destructor Documentation
model.ToroidalGrid.ToroidalGrid (int row, int column)
Definition at line 8 of file ToroidalGrid.java.
Referenced by model.ToroidalGrid.copyGrid().
Member Function Documentation
Grid model.ToroidalGrid.copyGrid ()
Definition at line 74 of file ToroidalGrid.java.
References model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), model.Grid.putCell(), and model.ToroidalGrid.ToroidalGrid().
List<Cell> model.ToroidalGrid.getAllNeighbors (int row, int col)
Definition at line 11 of file ToroidalGrid.java.
References model.Grid.getCell(), model.ToroidalGrid.getDirectNeighbors(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), and model.Grid.inBounds().
List<Cell> model.ToroidalGrid.getDirectNeighbors (int row, int col)
Definition at line 48 of file ToroidalGrid.java.
References model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), and model.Grid.inBounds().
Referenced by model.ToroidalGrid.getAllNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/ToroidalGrid.java