cellsociety_team10: controller.Packager Class Reference
controller.Packager Class Reference
Public Member Functions
Map< String, Integer > getPropertiesMap ()
Map< String, String > getColorMap ()
void setColorMap (Map< String, String > c)
void setPropertiesMap (Map< String, Integer > s)
Private Attributes
Map< String, Integer > attributeMap
Map< String, String > colorsMap
Detailed Description
Definition at line 8 of file Packager.java.
Member Function Documentation
Map<String, String> controller.Packager.getColorMap ()
Definition at line 21 of file Packager.java.
References controller.Packager.colorsMap.
Referenced by controller.Controller.loadFile().
Map<String,Integer> controller.Packager.getPropertiesMap ()
Definition at line 12 of file Packager.java.
Referenced by controller.Controller.listToGrid(), and controller.Controller.setDefaultParameters().
void controller.Packager.setColorMap (Map< String, String > c)
Definition at line 24 of file Packager.java.
Referenced by controller.XMLParser.parseColorMap().
void controller.Packager.setPropertiesMap (Map< String, Integer > s)
Definition at line 27 of file Packager.java.
Referenced by controller.XMLParser.parseGlobalParameters().
Member Data Documentation
Map<String,Integer> controller.Packager.attributeMap private
Definition at line 9 of file Packager.java.
Map<String, String> controller.Packager.colorsMap private
Definition at line 10 of file Packager.java.
Referenced by controller.Packager.getColorMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/controller/Packager.java