cellsociety_team10: viewPackage.View Class Reference
viewPackage.View Class Reference
Public Member Functions
View (Controller c, ResourceBundle resources)
void initialize (Stage primaryStage)
void createDisplayView (int x, int y)
void updateGridView (ViewPackager colorGrid)
void createErrorWindow (String st)
boolean getEdgeType ()
int getSpeed ()
void tryLoad (String file) throws ParserConfigurationException, SAXException, IOException
Protected Member Functions
void createGraphWindow ()
boolean getOutline ()
void addToRoot (Node n)
void setPlayAction ()
void setPause ()
void setStepSimulation ()
String getFileName ()
void setFileName (String file)
ResourceBundle getResourcePath ()
int getGeneration ()
Private Attributes
Integer DEFAULT_WINDOW_SIZE = 600
Group root
ResourceBundle myResources
String fileName =""
Controller control
ButtonBox buttons
ToggleBox toggles
DisplayGrid myGridDisplayed
PopulationGraph myGraph
int generation
Stage additionalStage
Detailed Description
Definition at line 19 of file View.java.
Constructor & Destructor Documentation
viewPackage.View.View (Controller c, ResourceBundle resources)
Definition at line 32 of file View.java.
Member Function Documentation
void viewPackage.View.addToRoot (Node n) protected
Definition at line 108 of file View.java.
Referenced by viewPackage.RectangularGridView.initialEmptyGrid(), and viewPackage.TriangularGridView.initialEmptyGrid().
void viewPackage.View.createDisplayView (int x, int y)
Definition at line 65 of file View.java.
References viewPackage.ToggleBox.getShape(), and viewPackage.DisplayGrid.initializeGridView().
Referenced by controller.Controller.loadFile().
void viewPackage.View.createErrorWindow (String st)
Definition at line 93 of file View.java.
References viewPackage.ErrorDisplay.display().
Referenced by controller.Controller.loadFile(), viewPackage.ButtonBox.loadFileBox(), and viewPackage.ButtonBox.makeSlider().
void viewPackage.View.createGraphWindow () protected
Definition at line 85 of file View.java.
References viewPackage.PopulationGraph.makeGraph().
Referenced by viewPackage.DisplayGrid.initializeGridView().
boolean viewPackage.View.getEdgeType ()
Definition at line 105 of file View.java.
References viewPackage.ToggleBox.getEdgeType().
Referenced by controller.Controller.listToGrid().
String viewPackage.View.getFileName () protected
Definition at line 122 of file View.java.
References viewPackage.View.fileName.
int viewPackage.View.getGeneration () protected
Definition at line 135 of file View.java.
References viewPackage.View.generation.
Referenced by viewPackage.PopulationGraph.updateGraph().
boolean viewPackage.View.getOutline () protected
Definition at line 101 of file View.java.
References viewPackage.ToggleBox.getOutline().
Referenced by viewPackage.DisplayGrid.outline().
ResourceBundle viewPackage.View.getResourcePath () protected
Definition at line 132 of file View.java.
References viewPackage.View.myResources.
Referenced by viewPackage.ButtonBox.ButtonBox().
int viewPackage.View.getSpeed ()
Definition at line 125 of file View.java.
References viewPackage.ButtonBox.getSpeed().
void viewPackage.View.initialize (Stage primaryStage)
Definition at line 40 of file View.java.
References viewPackage.ButtonBox.makeButtonBox(), viewPackage.ButtonBox.makeSlider(), and viewPackage.ToggleBox.makeToggles().
Referenced by controller.Controller.Controller().
void viewPackage.View.setFileName (String file) protected
Definition at line 129 of file View.java.
Referenced by viewPackage.ButtonBox.loadFileBox().
void viewPackage.View.setPause () protected
Definition at line 115 of file View.java.
References controller.Controller.stopSimulation().
Referenced by viewPackage.ButtonBox.makeButtonBox().
void viewPackage.View.setPlayAction () protected
Definition at line 111 of file View.java.
References controller.Controller.changeSpeed(), viewPackage.ButtonBox.getSpeed(), and controller.Controller.playSimulation().
Referenced by viewPackage.ButtonBox.makeButtonBox().
void viewPackage.View.setStepSimulation () protected
Definition at line 118 of file View.java.
References controller.Controller.stepSimulation().
Referenced by viewPackage.ButtonBox.makeButtonBox().
void viewPackage.View.tryLoad (String file) throws ParserConfigurationException, SAXException, IOException
Definition at line 138 of file View.java.
References controller.Controller.loadFile().
Referenced by viewPackage.ButtonBox.loadFileBox().
void viewPackage.View.updateGridView (ViewPackager colorGrid)
Definition at line 79 of file View.java.
References viewPackage.PopulationGraph.updateGraph(), and viewPackage.DisplayGrid.updateGrid().
Referenced by controller.Controller.loadFile(), and controller.Controller.stepSimulation().
Member Data Documentation
Stage viewPackage.View.additionalStage private
Definition at line 30 of file View.java.
ButtonBox viewPackage.View.buttons private
Definition at line 25 of file View.java.
Controller viewPackage.View.control private
Definition at line 24 of file View.java.
Integer viewPackage.View.DEFAULT_WINDOW_SIZE = 600 private
Definition at line 20 of file View.java.
String viewPackage.View.fileName ="" private
Definition at line 23 of file View.java.
Referenced by viewPackage.View.getFileName().
int viewPackage.View.generation private
Definition at line 29 of file View.java.
Referenced by viewPackage.View.getGeneration().
PopulationGraph viewPackage.View.myGraph private
Definition at line 28 of file View.java.
DisplayGrid viewPackage.View.myGridDisplayed private
Definition at line 27 of file View.java.
ResourceBundle viewPackage.View.myResources private
Definition at line 22 of file View.java.
Referenced by viewPackage.View.getResourcePath().
Group viewPackage.View.root private
Definition at line 21 of file View.java.
ToggleBox viewPackage.View.toggles private
Definition at line 26 of file View.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/View.java