cellsociety_team10: viewPackage.DisplayGrid Class Reference
viewPackage.DisplayGrid Class Reference abstract
Public Member Functions
DisplayGrid (View mainView)
void initializeGridView (int sizeX, int sizeY)
abstract void initialEmptyGrid (int xtot, int ytot, double x, double y)
void updateGrid (ViewPackager viewPackager)
void setToggleColorChange (Shape p)
Protected Member Functions
void outline (Shape p)
void setFill (Shape gridView, Color c)
View getView ()
void setShape (int row, int col, Shape p)
Private Member Functions
void setGridSize (int sizeX, int sizeY)
double determineXlength (int numCols)
double determineYlength (int numRows)
Private Attributes
final int totalWidthOfGrid = 350
final int totalHeightOfGrid = 350
int numSquareX = 0
int numSquareY = 0
View view
Shape[][] myGrid
Detailed Description
Definition at line 10 of file DisplayGrid.java.
Constructor & Destructor Documentation
viewPackage.DisplayGrid.DisplayGrid (View mainView)
Definition at line 19 of file DisplayGrid.java.
Member Function Documentation
double viewPackage.DisplayGrid.determineXlength (int numCols) private
Definition at line 37 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.initializeGridView().
double viewPackage.DisplayGrid.determineYlength (int numRows) private
Definition at line 41 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.initializeGridView().
View viewPackage.DisplayGrid.getView () protected
Definition at line 81 of file DisplayGrid.java.
References viewPackage.DisplayGrid.view.
Referenced by viewPackage.RectangularGridView.initialEmptyGrid(), and viewPackage.TriangularGridView.initialEmptyGrid().
abstract void viewPackage.DisplayGrid.initialEmptyGrid (int xtot, int ytot, double x, double y) abstract
Referenced by viewPackage.DisplayGrid.initializeGridView().
void viewPackage.DisplayGrid.initializeGridView (int sizeX, int sizeY)
Definition at line 29 of file DisplayGrid.java.
References viewPackage.View.createGraphWindow(), viewPackage.DisplayGrid.determineXlength(), viewPackage.DisplayGrid.determineYlength(), viewPackage.DisplayGrid.initialEmptyGrid(), and viewPackage.DisplayGrid.setGridSize().
Referenced by viewPackage.View.createDisplayView().
void viewPackage.DisplayGrid.outline (Shape p) protected
Definition at line 48 of file DisplayGrid.java.
References viewPackage.View.getOutline().
void viewPackage.DisplayGrid.setFill (Shape gridView, Color c) protected
Definition at line 77 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.setToggleColorChange(), and viewPackage.DisplayGrid.updateGrid().
void viewPackage.DisplayGrid.setGridSize (int sizeX, int sizeY) private
Definition at line 23 of file DisplayGrid.java.
References viewPackage.DisplayGrid.numSquareX, and viewPackage.DisplayGrid.numSquareY.
Referenced by viewPackage.DisplayGrid.initializeGridView().
void viewPackage.DisplayGrid.setShape (int row, int col, Shape p) protected
Definition at line 84 of file DisplayGrid.java.
Referenced by viewPackage.RectangularGridView.initialEmptyGrid(), and viewPackage.TriangularGridView.initialEmptyGrid().
void viewPackage.DisplayGrid.setToggleColorChange (Shape p)
Definition at line 65 of file DisplayGrid.java.
References viewPackage.DisplayGrid.setFill().
void viewPackage.DisplayGrid.updateGrid (ViewPackager viewPackager)
Definition at line 55 of file DisplayGrid.java.
References controller.ViewPackager.getColorGrid(), viewPackage.DisplayGrid.numSquareX, viewPackage.DisplayGrid.numSquareY, and viewPackage.DisplayGrid.setFill().
Referenced by viewPackage.View.updateGridView().
Member Data Documentation
Shape [][] viewPackage.DisplayGrid.myGrid private
Definition at line 16 of file DisplayGrid.java.
int viewPackage.DisplayGrid.numSquareX = 0 private
Definition at line 13 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.setGridSize(), and viewPackage.DisplayGrid.updateGrid().
int viewPackage.DisplayGrid.numSquareY = 0 private
Definition at line 14 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.setGridSize(), and viewPackage.DisplayGrid.updateGrid().
final int viewPackage.DisplayGrid.totalHeightOfGrid = 350 private
Definition at line 12 of file DisplayGrid.java.
final int viewPackage.DisplayGrid.totalWidthOfGrid = 350 private
Definition at line 11 of file DisplayGrid.java.
View viewPackage.DisplayGrid.view private
Definition at line 15 of file DisplayGrid.java.
Referenced by viewPackage.DisplayGrid.getView().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/DisplayGrid.java