cellsociety_team10: controller.XMLParser Class Reference
controller.XMLParser Class Reference
Public Member Functions
void parseXMLFile (String file) throws ParserConfigurationException, SAXException, IOException
ArrayList< ArrayList< CellState > > parseGrid (int r, int c) throws IllegalArgumentException, IndexOutOfBoundsException
int[] parseGridSize ()
Packager parseGlobalParameters ()
Packager parseColorMap ()
String parseSimulationName () throws NullPointerException
String parseSimulationTitle ()
String parseSimulationAuthor ()
Private Member Functions
void clean (Node node)
Private Attributes
Element root
Detailed Description
Definition at line 22 of file XMLParser.java.
Member Function Documentation
void controller.XMLParser.clean (Node node) private
Definition at line 106 of file XMLParser.java.
Referenced by controller.XMLParser.parseXMLFile().
Packager controller.XMLParser.parseColorMap ()
Definition at line 81 of file XMLParser.java.
References controller.Packager.setColorMap().
Referenced by controller.Controller.loadFile().
Packager controller.XMLParser.parseGlobalParameters ()
Definition at line 68 of file XMLParser.java.
References controller.Packager.setPropertiesMap().
Referenced by controller.Controller.loadFile().
ArrayList<ArrayList<CellState> > controller.XMLParser.parseGrid (int r, int c) throws IllegalArgumentException, IndexOutOfBoundsException
Definition at line 35 of file XMLParser.java.
Referenced by controller.Controller.loadFile().
int [] controller.XMLParser.parseGridSize ()
Definition at line 62 of file XMLParser.java.
Referenced by controller.Controller.loadFile().
String controller.XMLParser.parseSimulationAuthor ()
Definition at line 103 of file XMLParser.java.
String controller.XMLParser.parseSimulationName () throws NullPointerException
Definition at line 96 of file XMLParser.java.
Referenced by controller.Controller.loadFile().
String controller.XMLParser.parseSimulationTitle ()
Definition at line 100 of file XMLParser.java.
void controller.XMLParser.parseXMLFile (String file) throws ParserConfigurationException, SAXException, IOException
Definition at line 25 of file XMLParser.java.
References controller.XMLParser.clean().
Referenced by controller.Controller.loadFile().
Member Data Documentation
Element controller.XMLParser.root private
Definition at line 23 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/controller/XMLParser.java