cellsociety_team10: viewPackage.ButtonBox Class Reference
viewPackage.ButtonBox Class Reference
Public Member Functions
ButtonBox (View v)
int getSpeed ()
Protected Member Functions
HBox makeButtonBox ()
HBox makeSlider ()
Private Member Functions
Button makeButton (String name)
Text addText (String s, int size, int xLocation, int yLocation)
void loadFileBox ()
void updateSpeed (int s)
Private Attributes
View view
String fileName =""
double location
int input
Text speedText
Integer speed = 1
ResourceBundle myResources
Detailed Description
Definition at line 28 of file ButtonBox.java.
Constructor & Destructor Documentation
viewPackage.ButtonBox.ButtonBox (View v)
Definition at line 37 of file ButtonBox.java.
References viewPackage.View.getResourcePath().
Member Function Documentation
Text viewPackage.ButtonBox.addText (String s, int size, int xLocation, int yLocation) private
Definition at line 49 of file ButtonBox.java.
Referenced by viewPackage.ButtonBox.makeButtonBox(), and viewPackage.ButtonBox.makeSlider().
int viewPackage.ButtonBox.getSpeed ()
Definition at line 184 of file ButtonBox.java.
References viewPackage.ButtonBox.speed.
Referenced by viewPackage.View.getSpeed(), and viewPackage.View.setPlayAction().
void viewPackage.ButtonBox.loadFileBox () private
Definition at line 142 of file ButtonBox.java.
References viewPackage.View.createErrorWindow(), viewPackage.View.setFileName(), and viewPackage.View.tryLoad().
Referenced by viewPackage.ButtonBox.makeButtonBox().
Button viewPackage.ButtonBox.makeButton (String name) private
Definition at line 42 of file ButtonBox.java.
Referenced by viewPackage.ButtonBox.makeButtonBox().
HBox viewPackage.ButtonBox.makeButtonBox () protected
Definition at line 57 of file ButtonBox.java.
References viewPackage.ButtonBox.addText(), viewPackage.ButtonBox.loadFileBox(), viewPackage.ButtonBox.makeButton(), viewPackage.View.setPause(), viewPackage.View.setPlayAction(), and viewPackage.View.setStepSimulation().
Referenced by viewPackage.View.initialize().
HBox viewPackage.ButtonBox.makeSlider () protected
Definition at line 85 of file ButtonBox.java.
References viewPackage.ButtonBox.addText(), viewPackage.View.createErrorWindow(), and viewPackage.ButtonBox.updateSpeed().
Referenced by viewPackage.View.initialize().
void viewPackage.ButtonBox.updateSpeed (int s) private
Definition at line 188 of file ButtonBox.java.
Referenced by viewPackage.ButtonBox.makeSlider().
Member Data Documentation
String viewPackage.ButtonBox.fileName ="" private
Definition at line 30 of file ButtonBox.java.
int viewPackage.ButtonBox.input private
Definition at line 32 of file ButtonBox.java.
double viewPackage.ButtonBox.location private
Definition at line 31 of file ButtonBox.java.
ResourceBundle viewPackage.ButtonBox.myResources private
Definition at line 35 of file ButtonBox.java.
Integer viewPackage.ButtonBox.speed = 1 private
Definition at line 34 of file ButtonBox.java.
Referenced by viewPackage.ButtonBox.getSpeed().
Text viewPackage.ButtonBox.speedText private
Definition at line 33 of file ButtonBox.java.
View viewPackage.ButtonBox.view private
Definition at line 29 of file ButtonBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/ButtonBox.java