cellsociety_team10: controller.Controller Class Reference
controller.Controller Class Reference
Public Member Functions
Controller (Stage primaryStage)
void changeSpeed (int frameRate)
void playSimulation ()
void stepSimulation ()
void stopSimulation ()
void loadFile (String fileName) throws ParserConfigurationException, SAXException, IOException
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
Private Member Functions
void generateTimeline ()
ViewPackager bundleViewPackager (Grid next)
ArrayList< ArrayList< String > > createColorGrid (Grid gridToReturn)
Map< String, Integer > updateStateTotals (Grid gridToReturn)
void setDefaultParameters (String source, Packager Pack)
Packager validateParameters (String simName, Packager pack)
void setSimulationType (String name, Packager p, Grid g)
Grid listToGrid (ArrayList< ArrayList< CellState >> given, Packager properties)
Private Attributes
Simulation rules
View myView
Timeline myTimeline
Map< String, String > stateColorMap
ResourceBundle myResources
Static Private Attributes
static final int FRAME_MULTIPLIER = 4
Detailed Description
Definition at line 21 of file Controller.java.
Constructor & Destructor Documentation
controller.Controller.Controller (Stage primaryStage)
Definition at line 30 of file Controller.java.
References controller.Controller.generateTimeline(), and viewPackage.View.initialize().
Member Function Documentation
ViewPackager controller.Controller.bundleViewPackager (Grid next) private
Definition at line 65 of file Controller.java.
References controller.Controller.createColorGrid(), controller.ViewPackager.setColorGrid(), controller.ViewPackager.setStateTotalMap(), and controller.Controller.updateStateTotals().
Referenced by controller.Controller.loadFile(), and controller.Controller.stepSimulation().
void controller.Controller.changeSpeed (int frameRate)
Definition at line 44 of file Controller.java.
References controller.Controller.FRAME_MULTIPLIER, and controller.Controller.playSimulation().
Referenced by viewPackage.View.setPlayAction().
ArrayList<ArrayList<String> > controller.Controller.createColorGrid (Grid gridToReturn) private
Definition at line 72 of file Controller.java.
References model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), and model.Cell.toString().
Referenced by controller.Controller.bundleViewPackager().
void controller.Controller.generateTimeline () private
Definition at line 39 of file Controller.java.
Referenced by controller.Controller.Controller().
Grid controller.Controller.listToGrid (ArrayList< ArrayList< CellState >> given, Packager properties) private
Definition at line 178 of file Controller.java.
References viewPackage.View.getEdgeType(), controller.Packager.getPropertiesMap(), and model.Grid.putCell().
Referenced by controller.Controller.loadFile().
void controller.Controller.loadFile (String fileName) throws ParserConfigurationException, SAXException, IOException
Definition at line 109 of file Controller.java.
References controller.Controller.bundleViewPackager(), viewPackage.View.createDisplayView(), viewPackage.View.createErrorWindow(), controller.Packager.getColorMap(), controller.Controller.listToGrid(), controller.XMLParser.parseColorMap(), controller.XMLParser.parseGlobalParameters(), controller.XMLParser.parseGrid(), controller.XMLParser.parseGridSize(), controller.XMLParser.parseSimulationName(), controller.XMLParser.parseXMLFile(), controller.Controller.setSimulationType(), controller.Controller.stopSimulation(), viewPackage.View.updateGridView(), and controller.Controller.validateParameters().
Referenced by viewPackage.View.tryLoad().
void controller.Controller.playSimulation ()
Definition at line 54 of file Controller.java.
References controller.Controller.stepSimulation().
Referenced by controller.Controller.changeSpeed(), and viewPackage.View.setPlayAction().
void controller.Controller.setDefaultParameters (String source, Packager Pack) private
Definition at line 139 of file Controller.java.
References controller.Packager.getPropertiesMap().
Referenced by controller.Controller.validateParameters().
void controller.Controller.setSimulationType (String name, Packager p, Grid g) private
Definition at line 161 of file Controller.java.
Referenced by controller.Controller.loadFile().
void controller.Controller.stepSimulation ()
Definition at line 58 of file Controller.java.
References controller.Controller.bundleViewPackager(), model.Simulation.makeNextGrid(), model.Simulation.updateGrid(), and viewPackage.View.updateGridView().
Referenced by controller.Controller.playSimulation(), and viewPackage.View.setStepSimulation().
void controller.Controller.stopSimulation ()
Definition at line 103 of file Controller.java.
Referenced by controller.Controller.loadFile(), and viewPackage.View.setPause().
Map<String, Integer> controller.Controller.updateStateTotals (Grid gridToReturn) private
Definition at line 86 of file Controller.java.
References model.Grid.getCell(), model.Grid.getGridColSize(), model.Grid.getGridRowSize(), and model.Cell.toString().
Referenced by controller.Controller.bundleViewPackager().
Packager controller.Controller.validateParameters (String simName, Packager pack) private
Definition at line 148 of file Controller.java.
References controller.Controller.setDefaultParameters().
Referenced by controller.Controller.loadFile().
Member Data Documentation
final String controller.Controller.DEFAULT_RESOURCE_PACKAGE = "resources/" static
Definition at line 28 of file Controller.java.
final int controller.Controller.FRAME_MULTIPLIER = 4 static private
Definition at line 26 of file Controller.java.
Referenced by controller.Controller.changeSpeed().
ResourceBundle controller.Controller.myResources private
Definition at line 27 of file Controller.java.
Timeline controller.Controller.myTimeline private
Definition at line 24 of file Controller.java.
View controller.Controller.myView private
Definition at line 23 of file Controller.java.
Simulation controller.Controller.rules private
Definition at line 22 of file Controller.java.
Map<String, String> controller.Controller.stateColorMap private
Definition at line 25 of file Controller.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/controller/Controller.java