cellsociety_team10: viewPackage.PopulationGraph Class Reference
viewPackage.PopulationGraph Class Reference
Public Member Functions
PopulationGraph (View v)
Scene makeGraph ()
Protected Member Functions
void updateGraph (ViewPackager colorGrid)
Package Attributes
final NumberAxis xAxis
final NumberAxis yAxis
final LineChart< Number, Number > lineChart
Private Member Functions
void addToList (int l)
Private Attributes
View view
Object[] keys
List< XYChart.Series< Number, Number > > listOfSpecies
Detailed Description
Definition at line 17 of file PopulationGraph.java.
Constructor & Destructor Documentation
viewPackage.PopulationGraph.PopulationGraph (View v)
Definition at line 25 of file PopulationGraph.java.
References viewPackage.PopulationGraph.xAxis, and viewPackage.PopulationGraph.yAxis.
Member Function Documentation
void viewPackage.PopulationGraph.addToList (int l) private
Definition at line 57 of file PopulationGraph.java.
Referenced by viewPackage.PopulationGraph.updateGraph().
Scene viewPackage.PopulationGraph.makeGraph ()
Definition at line 33 of file PopulationGraph.java.
Referenced by viewPackage.View.createGraphWindow().
void viewPackage.PopulationGraph.updateGraph (ViewPackager colorGrid) protected
Definition at line 42 of file PopulationGraph.java.
References viewPackage.PopulationGraph.addToList(), viewPackage.View.getGeneration(), and controller.ViewPackager.getStateTotals().
Referenced by viewPackage.View.updateGridView().
Member Data Documentation
Object [] viewPackage.PopulationGraph.keys private
Definition at line 20 of file PopulationGraph.java.
final LineChart<Number,Number> viewPackage.PopulationGraph.lineChart package
Definition at line 23 of file PopulationGraph.java.
List<XYChart.Series<Number, Number> > viewPackage.PopulationGraph.listOfSpecies private
Definition at line 21 of file PopulationGraph.java.
View viewPackage.PopulationGraph.view private
Definition at line 19 of file PopulationGraph.java.
final NumberAxis viewPackage.PopulationGraph.xAxis package
Definition at line 22 of file PopulationGraph.java.
Referenced by viewPackage.PopulationGraph.PopulationGraph().
final NumberAxis viewPackage.PopulationGraph.yAxis package
Definition at line 22 of file PopulationGraph.java.
Referenced by viewPackage.PopulationGraph.PopulationGraph().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/viewPackage/PopulationGraph.java