cellsociety_team10: model.SegregationSimulation Class Reference
model.SegregationSimulation Class Reference
Public Member Functions
SegregationSimulation (Grid aGrid, Packager attributes)
CellState calculateNewCellState (int row, int col)
Grid makeNextGrid ()
Public Member Functions inherited from model.Simulation
Simulation (Grid aGrid, Packager attributes)
Grid getCurrentGrid ()
Grid getNextGrid ()
void setNextGrid (Grid x)
Grid makeNextGrid ()
void updateGrid (Grid x)
abstract CellState calculateNewCellState (int row, int col)
Private Attributes
ArrayList< Cell > cellsToMove
ArrayList< Point > emptyPlaces
Additional Inherited Members
Static Public Attributes inherited from model.Simulation
static final Random myGenerator = new Random(1234)
Package Attributes inherited from model.Simulation
Grid nextGrid
Detailed Description
Definition at line 11 of file SegregationSimulation.java.
Constructor & Destructor Documentation
model.SegregationSimulation.SegregationSimulation (Grid aGrid, Packager attributes)
Definition at line 15 of file SegregationSimulation.java.
Member Function Documentation
CellState model.SegregationSimulation.calculateNewCellState (int row, int col)
Definition at line 22 of file SegregationSimulation.java.
References model.CellState.EMPTY, model.Simulation.getCurrentGrid(), model.Grid.getDirectNeighborsWithType(), model.Cell.getKey(), and model.Cell.getState().
Grid model.SegregationSimulation.makeNextGrid ()
Definition at line 43 of file SegregationSimulation.java.
References model.CellState.EMPTY, model.Simulation.getCurrentGrid(), model.Simulation.myGenerator, model.Grid.print(), and model.Grid.putCell().
Member Data Documentation
ArrayList<Cell> model.SegregationSimulation.cellsToMove private
Definition at line 12 of file SegregationSimulation.java.
ArrayList<Point> model.SegregationSimulation.emptyPlaces private
Definition at line 13 of file SegregationSimulation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team10/repository/src/model/SegregationSimulation.java